server:
  port: 9000
spring:
  application:
    name: tzms-service-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.93.101:8848
    gateway:
      routes:
        - id: tzms-service-project
          uri: lb://tzms-service-project
          predicates:
            - Path=/project/**
        - id: tzms-service-auth
          uri: lb://tzms-service-auth
          predicates:
            - Path=/auth/**
management:
  endpoints:
    web:
      exposure:
        include: '*'