server:
  port: 8091
  servlet:
    context-path: /auth
spring:
  application:
    name: tzms-service-auth
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.180.122:8848
    sentinel:
      transport:
        dashboard: 192.168.180.122:8080
management:
  endpoints:
    web:
      exposure:
        include: '*'